"use client";
import {useEffect,useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {ArrowLeft,Check,MoreHorizontal,Plus,Send,Trash2,FileText} from "lucide-react";
import {calculateInvoiceTotals} from "../../../lib/domain/calculations";
import {calculateIndiaInvoiceTotals} from "../../../lib/domain/india-tax";
import styles from "./page.module.css";

type Item={id:number;description:string;qty:string;rate:string;tax:string;hsnSac:string};
type Project={id:string;name:string;code:string|null;status:string};
type GstProfile={registration_type:"REGULAR"|"COMPOSITION"|"UNREGISTERED"|"SEZ";gstin:string|null;state_code:string|null;default_place_of_supply:string|null;tax_inclusive_default:boolean;reverse_charge_default:boolean};
type State={code:string;name:string};
type TaxRule={id:string;name:string;code:string;tax_rate:number;hsn_sac:string|null;active:boolean};
const fallbackClients=[{id:"demo-acme",name:"Acme Studio",email:"accounts@acmestudio.co",address:"14 Residency Road, Bengaluru",gstin:"29AAACA1234A1Z5"},{id:"demo-northstar",name:"Northstar Media",email:"finance@northstar.media",address:"Mumbai, Maharashtra",gstin:"27AAACN8821D1Z2"}];
const money=(minor:bigint)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(minor)/100);
const uid=()=>Date.now()+Math.floor(Math.random()*1000);

export default function NewInvoicePage(){
 const pathname=usePathname(),isQuote=pathname.startsWith("/quotes"),documentType=isQuote?"QUOTE":"INVOICE",documentLabel=isQuote?"Quote":"Invoice";
 const [clients,setClients]=useState(fallbackClients),[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[client,setClient]=useState(fallbackClients[0]),[documentId,setDocumentId]=useState<string>(),[syncError,setSyncError]=useState(""),[invoiceNumber,setInvoiceNumber]=useState("INV-1"),[issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[dueDate,setDueDate]=useState(new Date(Date.now()+15*86400000).toISOString().slice(0,10));
 const [items,setItems]=useState<Item[]>([{id:1,description:"Brand strategy & creative direction",qty:"1",rate:"45000",tax:"18",hsnSac:""},{id:2,description:"Motion design support",qty:"2",rate:"7500",tax:"18",hsnSac:""}]);
 const [note,setNote]=useState(isQuote?"Quote valid until the date shown above.":"Payment due within 15 days of invoice date."),[saved,setSaved]=useState(true);
 const [gst,setGst]=useState<GstProfile|null>(null),[states,setStates]=useState<State[]>([]),[rules,setRules]=useState<TaxRule[]>([]),[taxMode,setTaxMode]=useState<"EXCLUSIVE"|"INCLUSIVE">("EXCLUSIVE"),[placeOfSupply,setPlaceOfSupply]=useState(""),[reverseCharge,setReverseCharge]=useState(false);
 const standardTotals=useMemo(()=>{try{return calculateInvoiceTotals(items.map(i=>({quantity:i.qty,unitPriceMinor:Math.round(Number(i.rate)*100),taxRate:i.tax})))}catch{return null}},[items]);
 const indiaTotals=useMemo(()=>{if(isQuote||!gst)return null;try{return calculateIndiaInvoiceTotals(items.map(i=>({description:i.description,quantity:i.qty,unitPriceMinor:Math.round(Number(i.rate)*100),taxRate:i.tax,hsnSac:i.hsnSac})),{sellerStateCode:gst.state_code,placeOfSupplyStateCode:placeOfSupply||gst.default_place_of_supply,taxMode,registrationType:gst.registration_type,reverseCharge})}catch{return null}},[items,isQuote,gst,placeOfSupply,taxMode,reverseCharge]);
 const validationError=useMemo(()=>{if(isQuote)return standardTotals?"":"Invoice contains invalid line-item values.";if(!gst)return "Configure the GST profile before issuing an invoice.";if(!placeOfSupply)return "Select a place of supply.";if(!indiaTotals){const missing=items.find(i=>!/^\d{4,8}$/.test(i.hsnSac));if(missing)return "Every invoice line needs a 4–8 digit HSN/SAC code.";return "Invoice contains invalid GST or line-item values."}return ""},[isQuote,standardTotals,gst,placeOfSupply,indiaTotals,items]);

 useEffect(()=>{const workspaceId=localStorage.getItem("finbooksos.workspace");if(!workspaceId)return;Promise.all([fetch("/api/clients?workspaceId="+encodeURIComponent(workspaceId)).then(r=>r.ok?r.json():null),fetch("/api/organizations",{cache:"no-store"}).then(r=>r.ok?r.json():null),fetch("/api/projects?workspaceId="+encodeURIComponent(workspaceId)).then(r=>r.ok?r.json():null),fetch("/api/gst/profile?workspaceId="+encodeURIComponent(workspaceId)).then(r=>r.ok?r.json():null),fetch("/api/gst/rules?workspaceId="+encodeURIComponent(workspaceId)).then(r=>r.ok?r.json():null)]).then(([c,o,p,g,rt])=>{if(c?.data?.length){setClients(c.data);setClient(c.data[0])}const orgs=o?.data??[];const selected=orgs.find((x:any)=>x.id===localStorage.getItem("finbooksos.organization"))??orgs[0];if(selected)setInvoiceNumber(String(selected.invoice_prefix||(isQuote?"QUO":"INV"))+String(selected.next_invoice_number||1));setProjects((p?.data??[]).filter((x:Project)=>x.status!=="ARCHIVED"));setRules((rt?.data??[]).filter((x:TaxRule)=>x.active));if(g?.data){setGst(g.data);setStates(g.states??[]);setTaxMode(g.data.tax_inclusive_default?"INCLUSIVE":"EXCLUSIVE");setReverseCharge(!!g.data.reverse_charge_default);setPlaceOfSupply(g.data.default_place_of_supply||g.data.state_code||"")}}).catch(()=>{})},[isQuote]);

 useEffect(()=>{const workspaceId=localStorage.getItem("finbooksos.workspace");if(!workspaceId)return;const timer=window.setTimeout(async()=>{setSaved(false);try{const r=await fetch("/api/documents/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:documentId,workspaceId,clientId:client.id.startsWith("demo-")?null:client.id,projectId:projectId||null,issueDate,dueDate,documentNumber:invoiceNumber,currency:"INR",documentType,payload:{client,items,note,tax:isQuote?undefined:{taxMode,placeOfSupplyStateCode:placeOfSupply,reverseCharge},totals:isQuote?(standardTotals?{subtotalMinor:standardTotals.subtotalMinor.toString(),taxMinor:standardTotals.taxMinor.toString(),totalMinor:standardTotals.totalMinor.toString()}:{subtotalMinor:"0",taxMinor:"0",totalMinor:"0"}):(indiaTotals?{subtotalMinor:indiaTotals.subtotalMinor.toString(),taxableMinor:indiaTotals.taxableMinor.toString(),taxMinor:indiaTotals.taxMinor.toString(),cgstMinor:indiaTotals.cgstMinor.toString(),sgstMinor:indiaTotals.sgstMinor.toString(),igstMinor:indiaTotals.igstMinor.toString(),totalMinor:indiaTotals.totalMinor.toString()}:{subtotalMinor:"0",taxMinor:"0",totalMinor:"0"})}})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.data?.id)setDocumentId(d.data.id);setSaved(true);setSyncError("")}catch(e){setSaved(false);setSyncError(e instanceof Error?e.message:"Sync failed")}},650);return()=>window.clearTimeout(timer)},[client,projectId,items,note,standardTotals,indiaTotals,documentId,invoiceNumber,issueDate,dueDate,documentType,taxMode,placeOfSupply,reverseCharge,isQuote]);

 async function issue(){const totals=isQuote?standardTotals:indiaTotals;if(!documentId||!totals||validationError)return;setSaved(false);try{const r=await fetch("/api/documents/issue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId,payload:{client,items,note,tax:isQuote?undefined:{taxMode,placeOfSupplyStateCode:placeOfSupply,reverseCharge},totals:isQuote?{subtotalMinor:standardTotals!.subtotalMinor.toString(),taxMinor:standardTotals!.taxMinor.toString(),totalMinor:standardTotals!.totalMinor.toString()}:{subtotalMinor:indiaTotals!.subtotalMinor.toString(),taxableMinor:indiaTotals!.taxableMinor.toString(),taxMinor:indiaTotals!.taxMinor.toString(),cgstMinor:indiaTotals!.cgstMinor.toString(),sgstMinor:indiaTotals!.sgstMinor.toString(),igstMinor:indiaTotals!.igstMinor.toString(),totalMinor:indiaTotals!.totalMinor.toString()}}})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(true);window.location.assign((isQuote?"/quotes/":"/invoices/")+d.data.id)}catch(e){setSyncError(e instanceof Error?e.message:"Unable to issue");setSaved(false)}}
 function update(id:number,key:keyof Item,value:string){setSaved(false);setItems(items.map(i=>i.id===id?{...i,[key]:value}:i))}
 function add(){setItems([...items,{id:uid(),description:"New service",qty:"1",rate:"0",tax:"18",hsnSac:""}]);setSaved(false)}
 function remove(id:number){setItems(items.filter(i=>i.id!==id));setSaved(false)}
 const shownTotal=isQuote?standardTotals?.totalMinor??0n:indiaTotals?.totalMinor??0n;

 return <main className={styles.page}>
  <header className={styles.topbar}><div className={styles.topLeft}><a href={isQuote?"/quotes":"/invoices"} className={styles.back} aria-label="Back"><ArrowLeft size={16}/></a><div><div className={styles.kicker}>{documentLabel}s / New</div><h1>New {documentLabel.toLowerCase()}</h1></div></div><div className={styles.topActions}><span className={saved?styles.saved:styles.saving}>{saved?<><Check size={13}/> Saved</>:<>{syncError||"Saving…"}</>}</span><button className={styles.ghost}><MoreHorizontal size={17}/></button><button className={styles.primary} disabled={!documentId||!!validationError||!((isQuote?standardTotals:indiaTotals))} onClick={issue}><Send size={15}/> Issue {documentLabel.toLowerCase()}</button></div></header>
  <div className={styles.workspace}><section className={styles.editor}>
   <div className={styles.section}><div className={styles.sectionHeader}><div><span className={styles.overline}>01</span><div><h2>Bill to</h2><p>Choose an existing client or create one.</p></div></div></div><div className={styles.clientGrid}>{clients.map(c=><button key={c.id} onClick={()=>setClient(c)} className={client.name===c.name?styles.clientActive:styles.clientCard}><span className={styles.clientAvatar}>{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.email}{c.gstin?" · "+c.gstin:""}</small></span>{client.name===c.name&&<Check size={15}/>}</button>)}<button className={styles.addClient}><Plus size={16}/><span><strong>Add client</strong><small>Create a new billing contact</small></span></button></div></div>
   <div className={styles.section}><div className={styles.fieldGrid}><label><span>Project</span><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.code?" · "+p.code:""}</option>)}</select></label><label><span>{documentLabel} number</span><input value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)}/></label><label><span>Issue date</span><input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)}/></label><label><span>{isQuote?"Valid until":"Due date"}</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div></div>
   {!isQuote&&<div className={styles.section}><div className={styles.sectionTitleRow}><div><span className={styles.overline}>02</span><div><h2>GST treatment</h2><p>Tax jurisdiction is captured into the immutable issue snapshot.</p></div></div></div><div className={styles.fieldGrid}><label><span>Place of supply</span><select value={placeOfSupply} onChange={e=>setPlaceOfSupply(e.target.value)}><option value="">Select state</option>{states.map(s=><option key={s.code} value={s.code}>{s.code} — {s.name}</option>)}</select></label><label><span>Tax mode</span><select value={taxMode} onChange={e=>setTaxMode(e.target.value as "EXCLUSIVE"|"INCLUSIVE")}><option value="EXCLUSIVE">Tax exclusive</option><option value="INCLUSIVE">Tax inclusive</option></select></label><label><span>Registration</span><input value={gst?.registration_type||"Not configured"} readOnly/></label><label><span>Reverse charge</span><select value={reverseCharge?"YES":"NO"} onChange={e=>setReverseCharge(e.target.value==="YES")}><option value="NO">No</option><option value="YES">Yes</option></select></label></div>{gst?.gstin&&<p style={{marginTop:10,fontSize:10,color:"#777"}}>GSTIN {gst.gstin} · Seller state {gst.state_code||"—"} · Supply is derived from seller/POS.</p>}</div>}
   <div className={styles.section}><div className={styles.sectionTitleRow}><div><span className={styles.overline}>{isQuote?"02":"03"}</span><div><h2>Line items</h2><p>{isQuote?"Amounts are calculated centrally.":"HSN/SAC and GST rate are part of the compliance record; tax arithmetic stays server/domain-owned."}</p></div></div><button className={styles.textButton} onClick={add}><Plus size={14}/> Add item</button></div>{validationError&&<div className={styles.validation}>{validationError}</div>}<div className={styles.lineItems}><div className={styles.lineHead}><span>Description</span><span>Qty</span><span>Rate</span>{!isQuote&&<span>HSN/SAC</span>}<span>Tax</span><span>Total</span><span/></div>{items.map((item,index)=>{const line=isQuote?null:indiaTotals?.lines[index];const lineTotal=line?line.taxableMinor+line.taxMinor:BigInt(Number.isFinite(Number(item.qty))&&Number.isFinite(Number(item.rate))?Math.max(0,Math.round(Number(item.qty)*Number(item.rate)*100)):0);return <div className={styles.lineRow} key={item.id} style={{gridTemplateColumns:isQuote?"minmax(180px,1fr) 58px 105px 68px 105px 34px":"minmax(160px,1fr) 52px 95px 82px 58px 105px 34px"}}><input className={styles.description} value={item.description} onChange={e=>update(item.id,"description",e.target.value)}/><input type="number" min="0" step="1" value={item.qty} onChange={e=>update(item.id,"qty",e.target.value)}/><div className={styles.moneyInput}><span>₹</span><input type="number" min="0" value={item.rate} onChange={e=>update(item.id,"rate",e.target.value)}/></div>{!isQuote&&<input value={item.hsnSac} placeholder="HSN/SAC" onChange={e=>update(item.id,"hsnSac",e.target.value.replace(/\D/g,"").slice(0,8))}/>}<select value={item.tax} onChange={e=>update(item.id,"tax",e.target.value)}>{rules.map(r=><option key={r.id} value={String(r.tax_rate)}>{r.tax_rate}%{r.name&&r.name!=="GST "+r.tax_rate+"%"?" · "+r.name:""}</option>)}</select><strong>{money(lineTotal)}</strong><button className={styles.iconButton} onClick={()=>remove(item.id)} aria-label="Remove item"><Trash2 size={14}/></button></div>})}</div></div>
   <div className={styles.section}><div className={styles.sectionTitleRow}><div><span className={styles.overline}>{isQuote?"03":"04"}</span><div><h2>Notes & terms</h2><p>Shown on the client-facing document.</p></div></div></div><textarea value={note} onChange={e=>setNote(e.target.value)}/></div>
  </section>
  <aside className={styles.summaryPane}><div className={styles.summaryHeader}><div><span>Document state</span><strong>{validationError?"Compliance review required":"Ready to issue"}</strong></div><FileText size={16}/></div><div className={styles.summaryBody}><div className={styles.summaryRow}><span>Client</span><b>{client.name}</b></div><div className={styles.summaryRow}><span>Items</span><b>{items.length}</b></div>{!isQuote&&<><div className={styles.summaryRow}><span>Taxable value</span><b>{money(indiaTotals?.taxableMinor??0n)}</b></div><div className={styles.summaryRow}><span>CGST</span><b>{money(indiaTotals?.cgstMinor??0n)}</b></div><div className={styles.summaryRow}><span>SGST</span><b>{money(indiaTotals?.sgstMinor??0n)}</b></div><div className={styles.summaryRow}><span>IGST</span><b>{money(indiaTotals?.igstMinor??0n)}</b></div></>}<div className={styles.summaryRow}><span>{isQuote?"Tax":"GST"}</span><b>{money(isQuote?standardTotals?.taxMinor??0n:indiaTotals?.taxMinor??0n)}</b></div><div className={styles.grandRow}><span>Total</span><b>{money(shownTotal)}</b></div></div><div className={styles.summaryNote}><span>COMPLIANCE</span><p>{isQuote?"Quote tax treatment remains provisional until conversion to an invoice.":"Issue stores seller state, place of supply, tax mode, HSN/SAC, tax components and validation warnings with the immutable document snapshot."}</p></div></aside>
  </div>
 </main>
}