"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,Check,ChevronDown,MoreHorizontal,Plus,Send,Trash2,FileText} from "lucide-react";
import {calculateInvoiceTotals} from "../../../lib/domain/calculations";
import styles from "./page.module.css";

type Item={id:number;description:string;qty:string;rate:string;tax:string};
const fallbackClients=[{id:"demo-acme",name:"Acme Studio",email:"accounts@acmestudio.co",address:"14 Residency Road, Bengaluru",gstin:"29AAACA1234A1Z5"},{id:"demo-northstar",name:"Northstar Media",email:"finance@northstar.media",address:"Mumbai, Maharashtra",gstin:"27AAACN8821D1Z2"}];
const money=(minor:bigint)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(minor)/100);
const uid=()=>Date.now()+Math.floor(Math.random()*1000);

export default function NewInvoicePage(){
 const [clients,setClients]=useState(fallbackClients),[client,setClient]=useState(fallbackClients[0]),[documentId,setDocumentId]=useState<string>(),[syncError,setSyncError]=useState(""),[invoiceNumber,setInvoiceNumber]=useState("INV-1"),[issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[dueDate,setDueDate]=useState(new Date(Date.now()+15*86400000).toISOString().slice(0,10));
 const [items,setItems]=useState<Item[]>([{id:1,description:"Brand strategy & creative direction — March retainer",qty:"1",rate:"45000",tax:"18"},{id:2,description:"Motion design support",qty:"2",rate:"7500",tax:"18"}]);
 const [note,setNote]=useState("Payment due within 15 days of invoice date."),[saved,setSaved]=useState(true);
 const totals=useMemo(()=>{try{return calculateInvoiceTotals(items.map(i=>({quantity:i.qty,unitPriceMinor:Math.round(Number(i.rate)*100),taxRate:i.tax})))}catch{return null}},[items]);
 const validationError=useMemo(()=>{if(totals)return "";const item=items.find(i=>!/^\+?\d+(?:\.\d+)?$/.test(i.qty)||Number(i.qty)<=0||!/^\+?\d+(?:\.\d+)?$/.test(i.rate)||Number(i.rate)<0||!/^\+?\d+(?:\.\d+)?$/.test(i.tax)||Number(i.tax)<0||Number(i.tax)>100||i.description.trim().length>1000);if(!item)return "Invoice contains invalid line-item values.";if(!item.description.trim())return "Each line item needs a description.";if(!/^\+?\d+(?:\.\d+)?$/.test(item.qty)||Number(item.qty)<=0)return "Quantity must be greater than zero.";if(!/^\+?\d+(?:\.\d+)?$/.test(item.rate)||Number(item.rate)<0)return "Rate must be zero or greater.";return "Tax must be between 0% and 100%."},[items]);

 useEffect(()=>{const workspaceId=localStorage.getItem("finbooksos.workspace");if(!workspaceId)return;Promise.all([fetch("/api/clients?workspaceId="+encodeURIComponent(workspaceId)).then(r=>r.ok?r.json():null),fetch("/api/organizations",{cache:"no-store"}).then(r=>r.ok?r.json():null)]).then(([c,o])=>{if(c?.data?.length){setClients(c.data);setClient(c.data[0])}const orgs=o?.data??[];const selected=orgs.find((x:any)=>x.id===localStorage.getItem("finbooksos.organization"))??orgs[0];if(selected)setInvoiceNumber(String(selected.invoice_prefix||"INV")+String(selected.next_invoice_number||1))}).catch(()=>{})},[]);
 useEffect(()=>{const workspaceId=localStorage.getItem("finbooksos.workspace");if(!workspaceId)return;const timer=window.setTimeout(async()=>{setSaved(false);try{const r=await fetch("/api/documents/draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:documentId,workspaceId,clientId:client.id.startsWith("demo-")?null:client.id,issueDate,dueDate,documentNumber:invoiceNumber,currency:"INR",payload:{client,items,note,totals:totals?{subtotalMinor:totals.subtotalMinor.toString(),taxMinor:totals.taxMinor.toString(),totalMinor:totals.totalMinor.toString()}:{subtotalMinor:"0",taxMinor:"0",totalMinor:"0"}}})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.data?.id)setDocumentId(d.data.id);setSaved(true);setSyncError("")}catch(e){setSaved(false);setSyncError(e instanceof Error?e.message:"Sync failed")}},650);return()=>window.clearTimeout(timer)},[client,items,note,totals,documentId,invoiceNumber,issueDate,dueDate]);

 async function issue(){if(!documentId||!totals||validationError)return;setSaved(false);try{const r=await fetch("/api/documents/issue",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId,payload:{client,items,note,totals:totals?{subtotalMinor:totals.subtotalMinor.toString(),taxMinor:totals.taxMinor.toString(),totalMinor:totals.totalMinor.toString()}:{subtotalMinor:"0",taxMinor:"0",totalMinor:"0"}}})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSaved(true);window.location.assign("/invoices/"+d.data.id)}catch(e){setSyncError(e instanceof Error?e.message:"Unable to issue");setSaved(false)}}
 function update(id:number,key:keyof Item,value:string){setSaved(false);setItems(items.map(i=>i.id===id?{...i,[key]:value}:i))}
 function add(){setItems([...items,{id:uid(),description:"New service",qty:"1",rate:"0",tax:"18"}]);setSaved(false)}
 function remove(id:number){setItems(items.filter(i=>i.id!==id));setSaved(false)}

 return <main className={styles.page}>
  <header className={styles.topbar}><div className={styles.topLeft}><a href="/invoices" className={styles.back} aria-label="Back to invoices"><ArrowLeft size={16}/></a><div><div className={styles.kicker}>Invoices / New</div><h1>New invoice</h1></div></div><div className={styles.topActions}><span className={saved?styles.saved:styles.saving}>{saved?<><Check size={13}/> Saved</>:<>{syncError||"Saving…"}</>}</span><button className={styles.ghost}><MoreHorizontal size={17}/></button><button className={styles.primary} disabled={!documentId||!totals||!!validationError} onClick={issue}><Send size={15}/> Issue invoice</button></div></header>
  <div className={styles.workspace}>
   <section className={styles.editor}>
    <div className={styles.section}><div className={styles.sectionHeader}><div><span className={styles.overline}>01</span><div><h2>Bill to</h2><p>Choose an existing client or create one.</p></div></div></div><div className={styles.clientGrid}>{clients.map(c=><button key={c.id} onClick={()=>setClient(c)} className={client.name===c.name?styles.clientActive:styles.clientCard}><span className={styles.clientAvatar}>{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.email}</small></span>{client.name===c.name&&<Check size={15}/>}</button>)}<button className={styles.addClient}><Plus size={16}/><span><strong>Add client</strong><small>Create a new billing contact</small></span></button></div></div>
    <div className={styles.section}><div className={styles.fieldGrid}><label><span>Invoice number</span><input value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)} /></label><label><span>Issue date</span><input type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)}/></label><label><span>Due date</span><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label><span>Currency</span><button className={styles.select}>INR — Indian Rupee <ChevronDown size={14}/></button></label></div></div>
    <div className={styles.section}><div className={styles.sectionTitleRow}><div><span className={styles.overline}>02</span><div><h2>Line items</h2><p>Amounts are calculated centrally; the editor only collects inputs.</p></div></div><button className={styles.textButton} onClick={add}><Plus size={14}/> Add item</button></div>{validationError&&<div className={styles.validation}>{validationError}</div>}<div className={styles.lineItems}><div className={styles.lineHead}><span>Description</span><span>Qty</span><span>Rate</span><span>Tax</span><span>Total</span><span/></div>{items.map(item=><div className={styles.lineRow} key={item.id}><input className={styles.description} value={item.description} onChange={e=>update(item.id,"description",e.target.value)}/><input type="number" min="0" step="1" value={item.qty} onChange={e=>update(item.id,"qty",e.target.value)}/><div className={styles.moneyInput}><span>₹</span><input type="number" min="0" value={item.rate} onChange={e=>update(item.id,"rate",e.target.value)}/></div><select value={item.tax} onChange={e=>update(item.id,"tax",e.target.value)}><option value="0">0%</option><option value="5">5%</option><option value="12">12%</option><option value="18">18%</option><option value="28">28%</option></select><strong>{money(BigInt(Number.isFinite(Number(item.qty))&&Number.isFinite(Number(item.rate))?Math.max(0,Math.round(Number(item.qty)*Number(item.rate)*100)):0))}</strong><button className={styles.iconButton} onClick={()=>remove(item.id)} aria-label="Remove item"><Trash2 size={14}/></button></div>)}</div></div>
    <div className={styles.section}><div className={styles.sectionTitleRow}><div><span className={styles.overline}>03</span><div><h2>Notes & terms</h2><p>Shown on the client-facing document.</p></div></div></div><textarea value={note} onChange={e=>setNote(e.target.value)} /></div>
   </section>
   <aside className={styles.summaryPane}>
    <div className={styles.summaryHeader}><div><span>Document state</span><strong>Ready to issue</strong></div><FileText size={16}/></div>
    <div className={styles.summaryBody}><div className={styles.summaryRow}><span>Client</span><b>{client.name}</b></div><div className={styles.summaryRow}><span>Items</span><b>{items.length}</b></div><div className={styles.summaryRow}><span>Subtotal</span><b>{money(totals?.subtotalMinor??0n)}</b></div><div className={styles.summaryRow}><span>GST</span><b>{money(totals?.taxMinor??0n)}</b></div><div className={styles.grandRow}><span>Total</span><b>{money(totals?.totalMinor??0n)}</b></div></div>
    <div className={styles.summaryNote}><span>PDF</span><p>Generated only from the issued document. No live preview is kept in the editor.</p></div>
   </aside>
  </div>
 </main>
}
