"use client";
import{useEffect,useState}from"react";import{KeyRound,Link2,Plus,Send,Webhook}from"lucide-react";import AppShell from"../../components/AppShell";import styles from"../settings/page.module.css";
export default function Integrations(){const[providers,setProviders]=useState<any[]>([]),[hooks,setHooks]=useState<any[]>([]),[keys,setKeys]=useState<any[]>([]),[name,setName]=useState("HTTP delivery"),[url,setUrl]=useState(""),[hookName,setHookName]=useState("FinBooks webhook"),[hookUrl,setHookUrl]=useState(""),[newKey,setNewKey]=useState(""),[error,setError]=useState("");
const w=typeof window!=="undefined"?localStorage.getItem("finbooksos.workspace"):null;
async function load(){if(!w)return;const q=encodeURIComponent(w);const rs=await Promise.all([fetch("/api/delivery-providers?workspaceId="+q),fetch("/api/webhooks?workspaceId="+q),fetch("/api/api-keys?workspaceId="+q)]);const ds=await Promise.all(rs.map(x=>x.json()));setProviders(ds[0].data??[]);setHooks(ds[1].data??[]);setKeys(ds[2].data??[])}useEffect(()=>{load()},[]);
async function createProvider(){const r=await fetch("/api/delivery-providers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,name,channel:"HTTP",providerKey:name.toLowerCase().replace(/\s+/g,"-"),endpointUrl:url})});const d=await r.json();if(!r.ok){setError(d.error);return}setUrl("");load()}
async function createHook(){const r=await fetch("/api/webhooks",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,name:hookName,endpointUrl:hookUrl,events:["DOCUMENT_ISSUED","PAYMENT_RECORDED","DELIVERY_QUEUED","DELIVERED","COMPLIANCE_ACCEPTED"]})});const d=await r.json();if(!r.ok){setError(d.error);return}setNewKey("Webhook secret — save now: "+d.secret);setHookUrl("");load()}
async function createApiKey(){const r=await fetch("/api/api-keys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,name:"External integration",scopes:["read"]})});const d=await r.json();if(!r.ok){setError(d.error);return}setNewKey("API key — save now: "+d.key);load()}
return <AppShell title="Integrations" subtitle="Provider boundaries, signed event delivery and scoped external API access. Secrets are shown once."><div className={styles.content}>
<section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><Link2 size={16}/></span><div><b>Delivery providers</b><small>HTTP adapters are explicit; no fake email/WhatsApp delivery is claimed.</small></div></div><div className={styles.formGrid}><label>Provider name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Endpoint URL<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://provider.example/send"/></label></div><button className={styles.save} style={{marginTop:12}} onClick={createProvider}><Plus size={13}/> Add provider</button>{providers.map(x=><div key={x.id} className={styles.notice}>{x.name} · {x.channel} · {x.active?"Active":"Disabled"}<br/><small>{x.endpoint_url}</small></div>)}</section>
<section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><Webhook size={16}/></span><div><b>Webhook endpoints</b><small>Integration events are queued before outbound delivery.</small></div></div><div className={styles.formGrid}><label>Name<input value={hookName} onChange={e=>setHookName(e.target.value)}/></label><label>Endpoint URL<input value={hookUrl} onChange={e=>setHookUrl(e.target.value)}/></label></div><button className={styles.save} style={{marginTop:12}} onClick={createHook}><Plus size={13}/> Add webhook</button>{hooks.map(x=><div key={x.id} className={styles.notice}>{x.name} · {x.active?"Active":"Disabled"}<br/><small>{x.endpoint_url}</small></div>)}</section>
<section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><KeyRound size={16}/></span><div><b>External API keys</b><small>Read-scoped v1 access for integrations. Keys are hashed and shown once.</small></div></div><button className={styles.save} onClick={createApiKey}><Plus size={13}/> Create read key</button>{keys.map(x=><div key={x.id} className={styles.notice}>{x.name} · {x.key_prefix}… · {x.revoked_at?"Revoked":"Active"}</div>)}</section>
{newKey&&<div className={styles.notice}><b>Copy this value now.</b><br/>{newKey}</div>}{error&&<div className={styles.error}>{error}</div>}
</div></AppShell>}