"use client";
import {useEffect,useMemo,useState} from "react";
import {Landmark,Plus,RefreshCw,ShieldCheck} from "lucide-react";
import AppShell from "../../components/AppShell";
import styles from "../settings/page.module.css";
type Rule={id:string;name:string;code:string;hsn_sac:string|null;description:string|null;tax_rate:number;active:boolean};
type Report={period:{from:string;to:string};documentCount:number;b2bCount:number;b2cCount:number;totals:{taxableMinor:number;cgstMinor:number;sgstMinor:number;igstMinor:number;cessMinor:number;invoiceValueMinor:number};hsnSummary:Array<{hsnSac:string;taxableMinor:number;taxMinor:number;count:number}>};
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(v/100);
export default function GstPage(){const [rules,setRules]=useState<Rule[]>([]),[report,setReport]=useState<Report|null>(null),[from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[name,setName]=useState("Standard GST 18%"),[code,setCode]=useState("GST18"),[rate,setRate]=useState("18"),[hsn,setHsn]=useState(""),[error,setError]=useState("");
 const workspace=typeof window!=="undefined"?localStorage.getItem("finbooksos.workspace"):null;
 async function loadRules(){if(!workspace)return;const r=await fetch("/api/gst/rules?workspaceId="+encodeURIComponent(workspace));const d=await r.json();setRules(d.data??[])}
 async function loadReport(){if(!workspace)return;const r=await fetch("/api/gst/report?workspaceId="+encodeURIComponent(workspace)+"&from="+from+"&to="+to);const d=await r.json();if(!r.ok){setError(d.error||"Unable to load report");return}setReport(d)}
 useEffect(()=>{loadRules();loadReport()},[]);
 async function addRule(){if(!workspace)return;const r=await fetch("/api/gst/rules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:workspace,name,code,taxRate:Number(rate),hsnSac:hsn||null})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to create rule");return}setName("Standard GST 18%");setCode("GST18");setRate("18");setHsn("");loadRules()}
 return <AppShell title="GST & Compliance" subtitle="India-ready tax rules, GST reporting foundations and provider-neutral compliance state."><div className={styles.content}>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><Landmark size={16}/></span><div><b>Tax rule catalogue</b><small>Rates are workspace data, not hard-coded into invoice UI.</small></div></div><div className={styles.formGrid}><label>Rule name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><label>Tax rate %<input type="number" min="0" max="100" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Default HSN/SAC<input value={hsn} onChange={e=>setHsn(e.target.value.replace(/\D/g,"").slice(0,8))}/></label></div><div style={{marginTop:12}}><button className={styles.save} onClick={addRule}><Plus size={13}/> Add rule</button></div><div className={styles.notice}>{rules.length?rules.map(r=><div key={r.id} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:"1px solid #29292d"}}><span>{r.name} · {r.code}{r.hsn_sac?" · HSN/SAC "+r.hsn_sac:""}</span><b>{r.tax_rate}%</b></div>):"No custom rules yet. Configure the GST profile first, then add the rates and HSN/SAC defaults your business actually uses."}</div></section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><RefreshCw size={16}/></span><div><b>GST reporting foundation</b><small>Period-scoped outward supply data with B2B/B2C and HSN summaries.</small></div></div><div className={styles.formGrid}><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div style={{marginTop:12}}><button className={styles.save} onClick={loadReport}>Refresh report</button></div>{report&&<><div className={styles.notice}><b>{report.documentCount}</b> invoices · <b>{report.b2bCount}</b> B2B · <b>{report.b2cCount}</b> B2C<br/>Taxable {money(report.totals.taxableMinor)} · CGST {money(report.totals.cgstMinor)} · SGST {money(report.totals.sgstMinor)} · IGST {money(report.totals.igstMinor)} · Invoice value {money(report.totals.invoiceValueMinor)}</div><div className={styles.notice}><b>HSN/SAC summary</b>{report.hsnSummary.map(x=><div key={x.hsnSac} style={{display:"flex",justifyContent:"space-between",padding:"7px 0"}}><span>{x.hsnSac}</span><span>{x.count} lines · {money(x.taxableMinor)} taxable · {money(x.taxMinor)} tax</span></div>)}</div></>}</section>
 <section className={styles.card}><div className={styles.cardHead}><span className={styles.icon}><ShieldCheck size={16}/></span><div><b>E-invoice / e-way bill architecture</b><small>Queue and callback boundaries exist; no provider is claimed to be connected.</small></div></div><div className={styles.notice}>Issued invoices first pass deterministic GST validation. A provider adapter can consume the stored compliance payload, submit it, then update ACCEPTED/REJECTED state through the callback boundary. Regulatory eligibility remains an explicit catalogue/configuration concern rather than a guessed threshold in the UI.</div></section>
 {error&&<div className={styles.error}>{error}</div>}</div></AppShell>}
