"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowDownLeft,ArrowUpRight,CheckCircle2,Plus,Search,WalletCards,X} from "lucide-react";
import AppShell from "../../components/AppShell";
import styles from "./page.module.css";
type Invoice={id:string;document_number:string;status:string;due_date:string|null;currency:string;draft_payload?:{totals?:{totalMinor?:string}};clients?:{name?:string|null}};
type Payment={id:string;payment_date:string;amount_minor:number;currency:string;method:string;reference:string|null;clients?:{name?:string|null};payment_allocations?:Array<{document_id:string;amount_minor:number;documents?:{document_number:string}|null}>};
const money=(v:number|string|undefined,currency="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency}).format(Number(v??0)/100);
export default function Payments(){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[payments,setPayments]=useState<Payment[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[invoiceId,setInvoiceId]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState("BANK_TRANSFER"),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[reference,setReference]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const workspace=()=>localStorage.getItem("finbooksos.workspace");
 async function load(){const w=workspace();if(!w)return;const [ir,pr]=await Promise.all([fetch("/api/documents?workspaceId="+encodeURIComponent(w)),fetch("/api/payments?workspaceId="+encodeURIComponent(w))]);const [id,pd]=await Promise.all([ir.json(),pr.json()]);setInvoices(id.data??[]);setPayments(pd.data??[])}
 useEffect(()=>{load().catch(()=>{})},[]);
 const filtered=useMemo(()=>invoices.filter(r=>(r.clients?.name??"").toLowerCase().includes(q.toLowerCase())||r.document_number.toLowerCase().includes(q.toLowerCase())),[invoices,q]);
 const selected=invoices.find(x=>x.id===invoiceId);const invoiceTotal=Number(selected?.draft_payload?.totals?.totalMinor??0);const paidForSelected=payments.filter(p=>p.payment_allocations?.some(a=>a.document_id===invoiceId)).reduce((s,p)=>s+Number(p.amount_minor),0);const remaining=Math.max(invoiceTotal-paidForSelected,0);
 async function record(){if(!invoiceId||!amount)return;setSaving(true);setError("");const r=await fetch("/api/payments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentId:invoiceId,amountMinor:Math.round(Number(amount)*100),paymentDate:date,method,reference})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to record payment");setSaving(false);return}setOpen(false);setAmount("");setReference("");await load();setSaving(false)}
 const recorded=payments.reduce((s,p)=>s+Number(p.amount_minor),0);
 return <AppShell title="Payments" subtitle="Record, reconcile and follow every incoming payment." action={<button className={styles.primary} onClick={()=>setOpen(true)}><Plus size={14}/> Record payment</button>}>
  <section className={styles.stats}><div><WalletCards size={16}/><span>Recorded</span><b>{money(recorded)}</b><small>{payments.length} payment entries</small></div><div><ArrowDownLeft size={16}/><span>Paid invoice value</span><b>{money(invoices.filter(x=>x.status==="PAID").reduce((s,x)=>s+Number(x.draft_payload?.totals?.totalMinor??0),0))}</b><small>Invoice state, not gateway data</small></div><div><ArrowUpRight size={16}/><span>Outstanding</span><b>{money(invoices.filter(x=>!["PAID","CANCELLED","VOID","DRAFT"].includes(x.status)).reduce((s,x)=>s+Number(x.draft_payload?.totals?.totalMinor??0),0)-recorded)}</b><small>Recorded allocation basis</small></div></section>
  <section className={styles.toolbar}><div className={styles.search}><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search invoice or client…"/></div></section>
  <div className={styles.table}><div className={styles.head}><span>Invoice</span><span>Client</span><span>Invoice value</span><span>State</span><span>Due</span></div>{filtered.map(r=><a className={styles.row} href={"/invoices/"+r.id} key={r.id}><b>{r.document_number}</b><span>{r.clients?.name??"Unassigned"}</span><strong>{money(r.draft_payload?.totals?.totalMinor,r.currency)}</strong><i className={r.status==="PAID"?styles.paid:styles.pending}>{r.status==="PAID"?"Paid":"Awaiting payment"}</i><small>{r.due_date??"—"}</small></a>)}</div>
  <div className={styles.payments}><div className={styles.paymentsTitle}><div><span>Ledger</span><b>Recorded payments</b></div><small>{payments.length} entries</small></div>{payments.length?payments.map(p=><a className={styles.paymentRow} href={"/receipts/"+p.id} key={p.id}><span className={styles.paymentIcon}><CheckCircle2 size={13}/></span><div><b>{p.clients?.name??"Client"}</b><small>{p.payment_allocations?.[0]?.documents?.document_number??"Unallocated"} · {p.method.replaceAll("_"," ")}</small></div><strong>{money(p.amount_minor,p.currency)}</strong><small>{p.payment_date}</small></a>):<div className={styles.noPayments}>No payments recorded yet.</div>}</div>
  {open&&<div className={styles.overlay} onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className={styles.modal}><button className={styles.close} onClick={()=>setOpen(false)}><X size={15}/></button><span className={styles.kicker}>Payments / Record</span><h2>Record incoming payment</h2><label>Invoice<select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">Choose invoice…</option>{invoices.filter(x=>!["DRAFT","PAID","CANCELLED","VOID"].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.document_number} — {x.clients?.name??"Client"}</option>)}</select></label>{selected&&<div className={styles.balance}><span>Remaining balance</span><b>{money(remaining,selected.currency)}</b></div>}<div className={styles.formGrid}><label>Amount<input type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="25000"/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="BANK_TRANSFER">Bank transfer</option><option value="UPI">UPI</option><option value="CARD">Card</option><option value="CASH">Cash</option><option value="CHEQUE">Cheque</option></select></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="UTR / transaction reference"/></label>{error&&<p className={styles.formError}>{error}</p>}<div className={styles.modalActions}><button onClick={()=>setOpen(false)}>Cancel</button><button className={styles.primary} disabled={saving||!invoiceId||!amount} onClick={record}>{saving?"Recording…":"Record payment"}</button></div></div></div>}
 </AppShell>
}
