"use client";
import {useEffect,useState} from "react";
import {Building2,Check,CreditCard,Globe2,ShieldCheck,Landmark} from "lucide-react";
import AppShell from "../../components/AppShell";
import styles from "./page.module.css";
type Profile={legal_name:string;display_name:string|null;email:string|null;phone:string|null;website:string|null;gstin:string|null;invoice_prefix:string;default_payment_terms_days:number;default_tax_rate:number};
type Gst={registration_type:"REGULAR"|"COMPOSITION"|"UNREGISTERED"|"SEZ";gstin:string|null;state_code:string|null;default_place_of_supply:string|null;tax_inclusive_default:boolean;reverse_charge_default:boolean;e_invoice_enabled:boolean;e_way_bill_enabled:boolean;e_invoice_provider:string|null;e_way_bill_provider:string|null};
type State={code:string;name:string};
export default function Settings(){
 const [profile,setProfile]=useState<Profile>({legal_name:"",display_name:"",email:"",phone:"",website:"",gstin:"",invoice_prefix:"INV",default_payment_terms_days:15,default_tax_rate:18});
 const [gst,setGst]=useState<Gst>({registration_type:"UNREGISTERED",gstin:"",state_code:"",default_place_of_supply:"",tax_inclusive_default:false,reverse_charge_default:false,e_invoice_enabled:false,e_way_bill_enabled:false,e_invoice_provider:"",e_way_bill_provider:""});
 const [states,setStates]=useState<State[]>([]),[saved,setSaved]=useState(false),[gstSaved,setGstSaved]=useState(false),[error,setError]=useState(""),[gstError,setGstError]=useState("");
 useEffect(()=>{const w=localStorage.getItem("finbooksos.workspace");if(!w)return;Promise.all([fetch("/api/business-profile?workspaceId="+encodeURIComponent(w)).then(r=>r.json()),fetch("/api/gst/profile?workspaceId="+encodeURIComponent(w)).then(r=>r.json())]).then(([b,g])=>{if(b.data)setProfile(p=>({...p,...b.data}));if(g.data)setGst(p=>({...p,...g.data}));setStates(g.states??[])}).catch(()=>{})},[]);
 function set<K extends keyof Profile>(k:K,v:Profile[K]){setProfile(p=>({...p,[k]:v}));setSaved(false)}
 function setG<K extends keyof Gst>(k:K,v:Gst[K]){setGst(p=>({...p,[k]:v}));setGstSaved(false)}
 async function save(){const w=localStorage.getItem("finbooksos.workspace");if(!w||!profile.legal_name){setError("Complete the legal business name first.");return}const r=await fetch("/api/business-profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,legalName:profile.legal_name,displayName:profile.display_name,email:profile.email,phone:profile.phone,website:profile.website,gstin:profile.gstin,invoicePrefix:profile.invoice_prefix,paymentTermsDays:profile.default_payment_terms_days,defaultTaxRate:profile.default_tax_rate})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to save");return}setSaved(true);setError("")}
 async function saveGst(){const w=localStorage.getItem("finbooksos.workspace");if(!w){setGstError("Workspace is required.");return}const r=await fetch("/api/gst/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,registrationType:gst.registration_type,gstin:gst.gstin,stateCode:gst.state_code,placeOfSupplyStateCode:gst.default_place_of_supply,taxInclusiveDefault:gst.tax_inclusive_default,reverseChargeDefault:gst.reverse_charge_default,eInvoiceEnabled:gst.e_invoice_enabled,eWayBillEnabled:gst.e_way_bill_enabled,eInvoiceProvider:gst.e_invoice_provider,eWayBillProvider:gst.e_way_bill_provider})});const d=await r.json();if(!r.ok){setGstError(d.error||"Unable to save GST profile");return}setGstSaved(true);setGstError("")}
 return <AppShell title="Settings" subtitle="Control business identity, document defaults and India compliance configuration." action={<button className={styles.save} onClick={save}>{saved?<><Check size={13}/> Saved</>:<>Save changes</>}</button>}>
 <div className={styles.layout}><nav className={styles.side}><a className={styles.active} href="#business">Business</a><a href="#documents">Documents</a><a href="#gst">GST & compliance</a><a href="#payments">Payments</a><a href="#security">Security</a></nav>
 <section className={styles.content}>
  <section className={styles.card} id="business"><div className={styles.cardHead}><span className={styles.icon}><Building2 size={16}/></span><div><b>Business identity</b><small>This is the issuer identity captured into future issued snapshots.</small></div></div><div className={styles.formGrid}><label>Legal business name<input value={profile.legal_name} onChange={e=>set("legal_name",e.target.value)} placeholder="Your legal name"/></label><label>Display name<input value={profile.display_name??""} onChange={e=>set("display_name",e.target.value)} placeholder="Public-facing studio name"/></label><label>Email<input value={profile.email??""} onChange={e=>set("email",e.target.value)} placeholder="accounts@studio.com"/></label><label>Phone<input value={profile.phone??""} onChange={e=>set("phone",e.target.value)} placeholder="+91…"/></label><label>Website<input value={profile.website??""} onChange={e=>set("website",e.target.value)} placeholder="https://…"/></label><label>GSTIN<input value={profile.gstin??""} onChange={e=>set("gstin",e.target.value)} placeholder="GSTIN"/></label></div></section>
  <section className={styles.card} id="documents"><div className={styles.cardHead}><span className={styles.icon}><CreditCard size={16}/></span><div><b>Document defaults</b><small>Applied when creating a new invoice.</small></div></div><div className={styles.formGrid}><label>Invoice prefix<input value={profile.invoice_prefix} onChange={e=>set("invoice_prefix",e.target.value.toUpperCase())}/></label><label>Payment terms (days)<input type="number" value={profile.default_payment_terms_days} onChange={e=>set("default_payment_terms_days",Number(e.target.value))}/></label><label>Default GST rate<input type="number" value={profile.default_tax_rate} onChange={e=>set("default_tax_rate",Number(e.target.value))}/></label></div></section>
  <section className={styles.card} id="gst"><div className={styles.cardHead}><span className={styles.icon}><Landmark size={16}/></span><div><b>GST & compliance profile</b><small>Explicit jurisdiction data drives invoice tax treatment. Eligibility thresholds are not hard-coded.</small></div></div><div className={styles.formGrid}>
   <label>Registration type<select value={gst.registration_type} onChange={e=>setG("registration_type",e.target.value as Gst["registration_type"])}><option value="REGULAR">Regular</option><option value="COMPOSITION">Composition</option><option value="SEZ">SEZ</option><option value="UNREGISTERED">Unregistered</option></select></label>
   <label>GSTIN<input value={gst.gstin??""} onChange={e=>setG("gstin",e.target.value.toUpperCase())} placeholder="10XXXXXXXXXXXXX"/></label>
   <label>Seller state<select value={gst.state_code??""} onChange={e=>setG("state_code",e.target.value)}><option value="">Select state</option>{states.map(s=><option key={s.code} value={s.code}>{s.code} — {s.name}</option>)}</select></label>
   <label>Default place of supply<select value={gst.default_place_of_supply??""} onChange={e=>setG("default_place_of_supply",e.target.value)}><option value="">Select state</option>{states.map(s=><option key={s.code} value={s.code}>{s.code} — {s.name}</option>)}</select></label>
   <label>Default tax mode<select value={gst.tax_inclusive_default?"INCLUSIVE":"EXCLUSIVE"} onChange={e=>setG("tax_inclusive_default",e.target.value==="INCLUSIVE")}><option value="EXCLUSIVE">Tax exclusive</option><option value="INCLUSIVE">Tax inclusive</option></select></label>
   <label>Reverse charge default<select value={gst.reverse_charge_default?"YES":"NO"} onChange={e=>setG("reverse_charge_default",e.target.value==="YES")}><option value="NO">No</option><option value="YES">Yes</option></select></label>
  </div><div className={styles.notice}>The invoice engine derives intra-state vs inter-state treatment from seller state and place of supply, then records CGST/SGST/IGST into the immutable issue snapshot. HSN/SAC is required on invoice lines.</div><div style={{display:"flex",gap:8,marginTop:12,alignItems:"center"}}><button className={styles.save} onClick={saveGst}>{gstSaved?<><Check size={13}/> GST profile saved</>:<>Save GST profile</>}</button>{gstError&&<span style={{color:"#ff8e91",fontSize:9}}>{gstError}</span>}</div></section>
  <section className={styles.card} id="payments"><div className={styles.cardHead}><span className={styles.icon}><Globe2 size={16}/></span><div><b>Collection & currency</b><small>Payment gateway integrations are intentionally separate from manual recording.</small></div></div><div className={styles.notice}>Manual payments are recorded as financial facts and allocated to immutable invoices. Gateway integrations can be added later without changing this ledger.</div></section>
  <section className={styles.card} id="security"><div className={styles.cardHead}><span className={styles.icon}><ShieldCheck size={16}/></span><div><b>Workspace security</b><small>All financial tables are workspace-scoped through Supabase Row Level Security.</small></div></div></section>
  {error&&<div className={styles.error}>{error}</div>}
 </section></div></AppShell>
}