"use client";
import {useEffect,useState} from "react";
import {Building2,Check,CreditCard,Globe2,ShieldCheck} from "lucide-react";
import AppShell from "../../components/AppShell";
import styles from "./page.module.css";
type Profile={legal_name:string;display_name:string|null;email:string|null;phone:string|null;website:string|null;gstin:string|null;invoice_prefix:string;default_payment_terms_days:number;default_tax_rate:number};
export default function Settings(){
 const [profile,setProfile]=useState<Profile>({legal_name:"",display_name:"",email:"",phone:"",website:"",gstin:"",invoice_prefix:"INV",default_payment_terms_days:15,default_tax_rate:18});
 const [saved,setSaved]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const w=localStorage.getItem("finbooksos.workspace");if(!w)return;fetch("/api/business-profile?workspaceId="+encodeURIComponent(w)).then(r=>r.json()).then(d=>{if(d.data)setProfile(p=>({...p,...d.data}));}).catch(()=>{})},[]);
 function set<K extends keyof Profile>(k:K,v:Profile[K]){setProfile(p=>({...p,[k]:v}));setSaved(false)}
 async function save(){const w=localStorage.getItem("finbooksos.workspace");if(!w||!profile.legal_name){setError("Complete the legal business name first.");return}const r=await fetch("/api/business-profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,legalName:profile.legal_name,displayName:profile.display_name,email:profile.email,phone:profile.phone,website:profile.website,gstin:profile.gstin,invoicePrefix:profile.invoice_prefix,paymentTermsDays:profile.default_payment_terms_days,defaultTaxRate:profile.default_tax_rate})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to save");return}setSaved(true);setError("")}
 return <AppShell title="Settings" subtitle="Control the business identity and financial defaults used across documents." action={<button className={styles.save} onClick={save}>{saved?<><Check size={13}/> Saved</>:<>Save changes</>}</button>}>
 <div className={styles.layout}><nav className={styles.side}><a className={styles.active} href="#business">Business</a><a href="#documents">Documents</a><a href="#payments">Payments</a><a href="#security">Security</a></nav>
 <section className={styles.content}>
  <section className={styles.card} id="business"><div className={styles.cardHead}><span className={styles.icon}><Building2 size={16}/></span><div><b>Business identity</b><small>This is the issuer identity captured into future issued snapshots.</small></div></div><div className={styles.formGrid}><label>Legal business name<input value={profile.legal_name} onChange={e=>set("legal_name",e.target.value)} placeholder="Your legal name"/></label><label>Display name<input value={profile.display_name??""} onChange={e=>set("display_name",e.target.value)} placeholder="Public-facing studio name"/></label><label>Email<input value={profile.email??""} onChange={e=>set("email",e.target.value)} placeholder="accounts@studio.com"/></label><label>Phone<input value={profile.phone??""} onChange={e=>set("phone",e.target.value)} placeholder="+91…"/></label><label>Website<input value={profile.website??""} onChange={e=>set("website",e.target.value)} placeholder="https://…"/></label><label>GSTIN<input value={profile.gstin??""} onChange={e=>set("gstin",e.target.value)} placeholder="GSTIN"/></label></div></section>
  <section className={styles.card} id="documents"><div className={styles.cardHead}><span className={styles.icon}><CreditCard size={16}/></span><div><b>Document defaults</b><small>Applied when creating a new invoice.</small></div></div><div className={styles.formGrid}><label>Invoice prefix<input value={profile.invoice_prefix} onChange={e=>set("invoice_prefix",e.target.value.toUpperCase())}/></label><label>Payment terms (days)<input type="number" value={profile.default_payment_terms_days} onChange={e=>set("default_payment_terms_days",Number(e.target.value))}/></label><label>Default GST rate<input type="number" value={profile.default_tax_rate} onChange={e=>set("default_tax_rate",Number(e.target.value))}/></label></div></section>
  <section className={styles.card} id="payments"><div className={styles.cardHead}><span className={styles.icon}><Globe2 size={16}/></span><div><b>Collection & currency</b><small>Payment gateway integrations are intentionally separate from manual recording.</small></div></div><div className={styles.notice}>Manual payments are recorded as financial facts and allocated to immutable invoices. Gateway integrations can be added later without changing this ledger.</div></section>
  <section className={styles.card} id="security"><div className={styles.cardHead}><span className={styles.icon}><ShieldCheck size={16}/></span><div><b>Workspace security</b><small>All financial tables are workspace-scoped through Supabase Row Level Security.</small></div></div></section>
  {error&&<div className={styles.error}>{error}</div>}
 </section></div></AppShell>
}