"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus,Search,Receipt,WalletCards,X} from "lucide-react";
import AppShell from "../../components/AppShell";
import styles from "./page.module.css";
type Expense={id:string;expense_date:string;vendor:string|null;category:string;description:string|null;amount_minor:number;tax_minor:number;currency:string;payment_method:string|null};
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(v/100);
export default function Expenses(){
 const [rows,setRows]=useState<Expense[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[vendor,setVendor]=useState(""),[category,setCategory]=useState("General"),[description,setDescription]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const workspace=()=>localStorage.getItem("finbooksos.workspace");
 async function load(){const w=workspace();if(!w)return;const r=await fetch("/api/expenses?workspaceId="+encodeURIComponent(w));const d=await r.json();if(r.ok)setRows(d.data??[]);else setError(d.error||"Unable to load expenses")}
 useEffect(()=>{load().catch(()=>{})},[]);
 const filtered=useMemo(()=>rows.filter(r=>(r.vendor??"").toLowerCase().includes(q.toLowerCase())||r.category.toLowerCase().includes(q.toLowerCase())||(r.description??"").toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const total=rows.reduce((s,r)=>s+Number(r.amount_minor),0);
 async function add(){const w=workspace();if(!w||!amount)return;setSaving(true);const r=await fetch("/api/expenses",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:w,vendor,category,description,amountMinor:Math.round(Number(amount)*100),expenseDate:date})});const d=await r.json();if(!r.ok){setError(d.error||"Unable to save");setSaving(false);return}setRows([d.data,...rows]);setOpen(false);setVendor("");setDescription("");setAmount("");setSaving(false)}
 return <AppShell title="Expenses" subtitle="Capture business costs so reporting reflects the whole operation." action={<button className={styles.primary} onClick={()=>setOpen(true)}><Plus size={14}/> Add expense</button>}>
 <section className={styles.stats}><div><Receipt size={16}/><span>This period</span><b>{money(total)}</b><small>{rows.length} recorded expenses</small></div><div><WalletCards size={16}/><span>Categories</span><b>{new Set(rows.map(r=>r.category)).size}</b><small>Active expense categories</small></div><div><Receipt size={16}/><span>Tax tracked</span><b>{money(rows.reduce((s,r)=>s+Number(r.tax_minor),0))}</b><small>Recorded tax component</small></div></section>
 <div className={styles.toolbar}><div className={styles.search}><Search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search vendor, category or description…"/></div></div>
 <div className={styles.table}><div className={styles.head}><span>Date</span><span>Vendor / description</span><span>Category</span><span>Amount</span></div>{filtered.map(r=><div className={styles.row} key={r.id}><small>{r.expense_date}</small><div><b>{r.vendor||"Unspecified vendor"}</b><span>{r.description||"—"}</span></div><i>{r.category}</i><strong>{money(Number(r.amount_minor))}</strong></div>)}</div>
 {!filtered.length&&<div className={styles.empty}><Receipt size={18}/><b>{rows.length?"No matching expenses":"No expenses recorded"}</b><span>Record software, travel, contractors and operating costs as they happen.</span></div>}
 {open&&<div className={styles.overlay} onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><div className={styles.modal}><button className={styles.close} onClick={()=>setOpen(false)}><X size={15}/></button><span className={styles.kicker}>Expenses / New</span><h2>Record expense</h2><div className={styles.formGrid}><label>Vendor<input value={vendor} onChange={e=>setVendor(e.target.value)} placeholder="Adobe"/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className={styles.formGrid}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option>General</option><option>Software</option><option>Travel</option><option>Contractors</option><option>Marketing</option><option>Office</option><option>Professional services</option></select></label><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="2500"/></label></div><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Monthly software subscription"/></label>{error&&<p className={styles.error}>{error}</p>}<div className={styles.modalActions}><button onClick={()=>setOpen(false)}>Cancel</button><button className={styles.primary} disabled={saving||!amount} onClick={add}>{saving?"Saving…":"Save expense"}</button></div></div></div>}
 </AppShell>
}