import {NextResponse} from "next/server";import {createClient} from "../../../../lib/supabase/server";
import {validateInvoiceInput} from "../../../../lib/domain/calculations";
export async function POST(request:Request){const supabase=await createClient();const {data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json();if(!body.documentId)return NextResponse.json({error:"Document is required"},{status:400});
const doc=await supabase.from("documents").select("*,clients(*)").eq("id",body.documentId).single();if(doc.error)return NextResponse.json({error:doc.error.message},{status:404});
const profile=await supabase.from("business_profiles").select("*").eq("workspace_id",doc.data.workspace_id).single();if(profile.error||!profile.data)return NextResponse.json({error:profile.error?.message||"Business profile not found"},{status:400});
const workspace=await supabase.from("workspaces").select("organization_id").eq("id",doc.data.workspace_id).maybeSingle();
const organization=workspace.data?.organization_id?await supabase.from("organizations").select("*").eq("id",workspace.data.organization_id).maybeSingle():{data:null};
const payload=body.payload||doc.data.draft_payload;
try{validateInvoiceInput(payload?.items)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Invalid invoice lines"},{status:400})}
const issuer=organization.data||profile.data;const snapshot={issuer,recipient:doc.data.clients,lines:payload.items||[],currency:{code:doc.data.currency,scale:2,symbol:doc.data.currency==="INR"?"₹":doc.data.currency},paymentInstructions:profile.data.payment_details,document:{number:doc.data.document_number,issueDate:doc.data.issue_date,dueDate:doc.data.due_date,type:doc.data.type},templateVersion:"default-v1",layoutVersion:"a4-v1",compliance:{}};const {data,error}=await supabase.rpc("issue_document",{target_document:body.documentId,issued_payload:payload,issued_snapshot:snapshot});if(error||!data)return NextResponse.json({error:error?.message||"Unable to issue document"},{status:400});return NextResponse.json({data,snapshot,publicUrl:`${new URL(request.url).origin}/invoice/${data.public_token}`})}