"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowDownToLine,ArrowRight,Building2,FileText,LockKeyhole,LogOut,Receipt,WalletCards} from "lucide-react";

type Period="month"|"3months"|"6months"|"fy"|"all";
type Filter="all"|"paid"|"open"|"overdue"|"partial";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const date=(s:string)=>s?new Date(s+"T00:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"";
function inPeriod(s:string,p:Period){const d=new Date(s+"T00:00:00"),now=new Date();if(p==="all")return true;if(p==="month")return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();const months=p==="3months"?3:p==="6months"?6:0;if(months){const start=new Date(now.getFullYear(),now.getMonth()-months+1,1);return d>=start}const fyStart=new Date(now.getMonth()>=3?now.getFullYear():now.getFullYear()-1,3,1);return d>=fyStart}
function matches(i:any,f:Filter){if(f==="all")return true;if(f==="paid")return i.balance<=0;if(f==="overdue")return i.is_overdue&&i.balance>0;if(f==="partial")return i.paid>0&&i.balance>0;return i.balance>0&&!i.is_overdue}

export default function Portal({params}:{params:Promise<{slug:string}>}){
 const [slug,setSlug]=useState(""),[data,setData]=useState<any>(null),[password,setPassword]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[period,setPeriod]=useState<Period>("all"),[filter,setFilter]=useState<Filter>("all");
 useEffect(()=>{params.then(p=>setSlug(p.slug))},[params]);
 useEffect(()=>{if(slug)load()},[slug]);
 async function load(){const r=await fetch("/api/client-portal/data?slug="+encodeURIComponent(slug),{cache:"no-store"});if(r.ok)setData(await r.json())}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch("/api/client-portal/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({slug,password})});const j=await r.json();setBusy(false);if(!r.ok){setError(j.error||"Could not sign in.");return}await load()}
 const invoices=useMemo(()=>data?.invoices??[],[data]);const payments=useMemo(()=>data?.payments??[],[data]);
 const scoped=invoices.filter((i:any)=>inPeriod(i.issue_date,period)&&matches(i,filter));const periodInvoices=invoices.filter((i:any)=>inPeriod(i.issue_date,period));
 const billed=periodInvoices.reduce((s:number,i:any)=>s+i.total,0),paid=periodInvoices.reduce((s:number,i:any)=>s+i.paid,0),outstanding=invoices.reduce((s:number,i:any)=>s+i.balance,0);
 if(!data)return <main className="portal-screen"><div className="portal-card"><div className="portal-kicker">SECURE CLIENT ACCOUNT</div><h1>Open your account</h1><p>Enter the password provided by the organisation.</p><form className="portal-login" onSubmit={login}><label>Password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="portal-login-error">{error}</div>}<button className="portal-button dark" disabled={busy}>{busy?"Signing in…":"Open account"}</button></form></div></main>;
 return <main className="portal-screen"><div className="portal-shell">
  <header className="portal-header"><div><div className="portal-brand">{data.organization?.logo_url?<img className="portal-org-logo" src={data.organization.logo_url} alt=""/>:<Building2 size={14}/>}<strong>{data.organization?.name||"Organisation"}</strong></div><h1>{data.client?.legal_name||data.client?.name}</h1><p>{data.client?.email||"Secure financial workspace"}</p></div><div className="portal-actions"><a className="portal-button dark" href={"/api/client-portal/"+slug+"/statement?period=all"}><ArrowDownToLine size={14}/>Full statement</a><button className="portal-button" onClick={async()=>{await fetch("/api/client-portal/logout",{method:"POST"});setData(null)}}><LogOut size={14}/>Sign out</button></div></header>
  <section className="portal-controls"><div className="portal-period"><span>Period</span>{(["month","3months","6months","fy","all"] as Period[]).map(p=><button key={p} className={period===p?"active":""} onClick={()=>setPeriod(p)}>{p==="month"?"This month":p==="3months"?"Last 3 months":p==="6months"?"Last 6 months":p==="fy"?"Financial year":"All time"}</button>)}</div><div className="portal-period"><span>Status</span>{(["all","open","overdue","partial","paid"] as Filter[]).map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f==="open"?"Outstanding":f==="partial"?"Partially paid":f[0].toUpperCase()+f.slice(1)}</button>)}</div></section>
  <section className="portal-position"><div><span>OUTSTANDING</span><strong>{money(outstanding)}</strong><small>{invoices.filter((i:any)=>i.is_overdue&&i.balance>0).length} overdue</small></div><div className="portal-position-facts"><span>Billed <b>{money(billed)}</b></span><span>Paid <b>{money(paid)}</b></span><span>Shown <b>{scoped.length}</b></span></div><a className="portal-button dark" href={"/api/client-portal/"+slug+"/statement?period="+period}><FileText size={14}/>Statement</a></section>
  <section className="portal-panel"><div className="portal-panel-head"><div><h2>Invoices</h2><span>{scoped.length} records</span></div><Receipt size={16}/></div>{scoped.length?scoped.map((i:any)=><a className="portal-row" key={i.id} href={"/portal/"+slug+"/invoice/"+i.id}><div><b>#{i.document_number}</b><span>{date(i.issue_date)}{i.due_date?" · Due "+date(i.due_date):""}</span></div><div><strong>{money(i.total)}</strong><small>{i.balance>0?money(i.balance)+" outstanding":"Paid"}</small></div><ArrowRight size={15}/></a>):<div className="portal-empty">No invoices match these filters.</div>}</section>
  <section className="portal-panel"><div className="portal-panel-head"><div><h2>Payments</h2><span>{payments.length} recorded</span></div><WalletCards size={16}/></div>{payments.length?payments.map((p:any)=><a className="portal-row" key={p.id} href={"/api/client-portal/"+slug+"/receipt/"+p.id}><div><b>{money(p.amount)}</b><span>{date(p.payment_date)} · {String(p.method||"").replaceAll("_"," ")}</span></div><div><strong>{p.reference||"Recorded"}</strong><small>Download receipt</small></div><ArrowRight size={15}/></a>):<div className="portal-empty">No payments recorded yet.</div>}</section>
  <footer className="portal-footer">Secure client account · {data.organization?.name||""}</footer>
 </div></main>
}
